shared:
  # How often should you poll to check whether a system should be scaled
  # in seconds
  poolWindow: 10
  
components:
  - name: "runner"
    query: "select * from test_table1"
    min: 0
    max: 1